"""Add AI batch jobs

Revision ID: 053bf5eb03b2
Revises: 133d6fced962
Create Date: 2026-05-20 14:40:57.288594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053bf5eb03b2'
down_revision = '133d6fced962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_batch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('openai_batch_id', sa.String(length=255), nullable=False),
    sa.Column('input_file_id', sa.String(length=255), nullable=True),
    sa.Column('output_file_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('insights_created', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_run_id'], ['source_run_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_batch_jobs')
    # ### end Alembic commands ###
