"""Add company aliases

Revision ID: 133d6fced962
Revises: 59e7940ea3d0
Create Date: 2026-05-20 14:07:02.835519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133d6fced962'
down_revision = '59e7940ea3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_aliases')
    # ### end Alembic commands ###
