"""Add signal review workflow

Revision ID: 59e7940ea3d0
Revises: cf8088cb387c
Create Date: 2026-05-20 11:06:08.432286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e7940ea3d0'
down_revision = 'cf8088cb387c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_signals', schema=None) as batch_op:
        batch_op.drop_column('review_notes')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
